# Generated by Django 4.2 on 2023-04-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('time', models.TimeField(verbose_name='Время')),
                ('date', models.DateField(verbose_name='Дата')),
                ('location', models.CharField(max_length=20, verbose_name='Локация')),
                ('rate', models.CharField(max_length=20, verbose_name='Тариф')),
            ],
        ),
    ]
